#!/usr/bin/bash

MINDUSTRY_PATH="/home/norax/.local/share/Mindustry/mods"
LAUNCHER="/home/norax/GOG Games/mindustry/start.sh"


./gradlew build
cp build/libs/* "$MINDUSTRY_PATH"


"$LAUNCHER" --version relase
