#!/usr/bin/bash
clear
MINDUSTRY_PATH="/home/norax/.local/share/Mindustry/mods"
LAUNCHER="/home/norax/GOG Games/mindustry/start.sh"

./gradlew build
RESULT=$?

if [ $RESULT -eq 0 ]; then
    cp build/libs/* "$MINDUSTRY_PATH"
    "$LAUNCHER" --version relase
fi